# Generated by Django 4.0 on 2022-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdd_pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=100)),
                ('identifier', models.IntegerField()),
                ('assignee', models.CharField(max_length=100)),
                ('finished', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pictureinfo',
            name='center',
            field=models.CharField(choices=[('0750', '750'), ('0775', '775'), ('0800', '800'), ('0825', '825'), ('0850', '850'), ('0875', '875'), ('0900', '900'), ('0925', '925'), ('0950', '950')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pictureinfo',
            name='leftBeginning',
            field=models.CharField(choices=[('0750', '750'), ('0775', '775'), ('0800', '800'), ('0825', '825'), ('0850', '850'), ('0875', '875'), ('0900', '900'), ('0925', '925'), ('0950', '950')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pictureinfo',
            name='rightBeginning',
            field=models.CharField(choices=[('0750', '750'), ('0775', '775'), ('0800', '800'), ('0825', '825'), ('0850', '850'), ('0875', '875'), ('0900', '900'), ('0925', '925'), ('0950', '950')], max_length=32, null=True),
        ),
    ]
